version: '3.9'
services:
  app:
    build: .
    image: hitech-market/web
    container_name: hitech-market-web
    restart: always
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80
    ports:
      - "8080:80"
    networks:
      - hitech-market

networks:
  hitech-market: null
